// Code generated by hertz generator.

package interaction

import (
	"context"

	interaction "TikTok/biz/model/interaction"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// LikeVideo .
// @router /like/action [POST]
func LikeVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interaction.LikeVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(interaction.LikeVideoResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetLikeList .
// @router /like/list [GET]
func GetLikeList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interaction.GetLikeListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(interaction.GetLikeListResponse)

	c.JSON(consts.StatusOK, resp)
}

// CommentVideo .
// @router /comment/pubilsh [POST]
func CommentVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interaction.CommentVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(interaction.CommentVideoResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetCommentList .
// @router /comment/list [GET]
func GetCommentList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interaction.GetCommentListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(interaction.GetCommentListResponse)

	c.JSON(consts.StatusOK, resp)
}

// DeleteComment .
// @router /comment/delete [POST]
func DeleteComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interaction.DeleteCommentRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(interaction.DeleteCommentResponse)

	c.JSON(consts.StatusOK, resp)
}
