// Code generated by hertz generator.

package interaction

import (
	"context"
	"errors"
	"log"
	"net/http"
	"strconv"
	"time"

	interaction "TikTok/biz/model/interaction"
	"TikTok/biz/model/video"
	"TikTok/dal/mysql"
	myredis "TikTok/dal/redis"
	myutils "TikTok/utils"

	"TikTok/mw/token"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"gorm.io/gorm"
)

// LikeVideo .
// @router /like/action [POST]
func LikeVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interaction.LikeVideoRequest
	err = c.BindAndValidate(&req)

	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	if req.ActionType != 1 && req.ActionType != 2 {
		c.String(consts.StatusBadRequest, "invalid action type")
		return
	}

	Likekey := "like:video:" + req.VideoId
	LikeUserKey := "like:users:" + req.VideoId

	// 第一层：缓存命中，直接操作 Redis
	Like, err := myredis.Rdb.Get(context.Background(), Likekey).Result()
	if err == nil && Like != "" {
		// 缓存命中，直接处理点赞/取消点赞
		if req.ActionType == 1 {
			// 检查用户是否已经点赞（使用 Redis SET）
			isLiked, _ := myredis.Rdb.SIsMember(context.Background(), LikeUserKey, req.UserId).Result()
			if isLiked {
				c.String(consts.StatusConflict, "你已经点赞过了")
				return
			}

			// 更新 Redis 缓存
			if err := myredis.Rdb.Incr(context.Background(), Likekey).Err(); err != nil {
				c.String(consts.StatusInternalServerError, "内存点赞失败")
				log.Println(err)
				return
			}

			myredis.Rdb.SAdd(context.Background(), LikeUserKey, req.UserId)

			// 异步写入数据库
			go func() {
				var likevideo video.Video
				mysql.Db.Model(&video.Video{}).Where("video_id = ?", req.VideoId).First(&likevideo)
				newLike := video.VideoLiker{
					UserId: req.UserId,
					Video:  &likevideo,
				}
				mysql.Db.Model(&video.VideoLiker{}).Create(&newLike)
			}()
		} else {
			// 检查用户是否点赞过
			isLiked, _ := myredis.Rdb.SIsMember(context.Background(), LikeUserKey, req.UserId).Result()
			if !isLiked {
				c.String(consts.StatusConflict, "你还没有点赞过")
				return
			}

			// 更新 Redis 缓存
			if err := myredis.Rdb.Decr(context.Background(), Likekey).Err(); err != nil {
				c.String(consts.StatusInternalServerError, "取消点赞失败")
				log.Println(err)
				return
			}

			// 从点赞集合中移除用户
			myredis.Rdb.SRem(context.Background(), LikeUserKey, req.UserId)

			// 异步删除数据库记录
			go func() {
				mysql.Db.Where("user_id = ? AND video_id = ?", req.UserId, req.VideoId).Delete(&video.VideoLiker{})
			}()
		}

		// 异步更新数据库点赞数
		go mysql.UpdateVideoLikeCount(req.VideoId, myredis.Rdb.Get(context.Background(), Likekey).Val())
	} else {
		//：缓存未命中，从数据库获取并写入缓存
		var videoInfo video.Video
		err := mysql.Db.Model(&video.Video{}).Where("Video_Id = ?", req.VideoId).First(&videoInfo).Error
		if err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				c.String(consts.StatusNotFound, "video not found")
				return
			}
			c.String(consts.StatusInternalServerError, "database error")
			return
		}

		// 写入 Redis 缓存（24小时过期）
		Like = strconv.FormatInt(videoInfo.LikeCount, 10)
		if err = myredis.Rdb.Set(context.Background(), Likekey, Like, 24*time.Hour).Err(); err != nil {
			c.String(consts.StatusInternalServerError, "设置缓存失败")
			return
		}

		// 从数据库加载点赞用户列表到
		var likeUsers []video.VideoLiker
		mysql.Db.Model(&video.VideoLiker{}).Where("video_id = ?", req.VideoId).Find(&likeUsers)
		for _, user := range likeUsers {
			myredis.Rdb.SAdd(context.Background(), LikeUserKey, user.UserId)
		}
		myredis.Rdb.Expire(context.Background(), LikeUserKey, 24*time.Hour)

		// 递归调用，此时缓存已命中，走第一层逻辑
		LikeVideo(ctx, c)
		return
	}

	// 更新 Redis 排行榜
	myredis.Rdb.ZIncrBy(ctx, "video_list", 1, req.VideoId)
	// 更新数据库访问量
	mysql.UpdateVideoVisitCount(req.VideoId)

	resp := new(interaction.LikeVideoResponse)
	resp.BaseResponse = &interaction.BaseResponse{
		StatusCode: http.StatusOK,
		StatusMsg:  "success",
	}
	c.JSON(consts.StatusOK, resp)
}

// GetLikeList .
// @router /like/list [GET]
func GetLikeList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interaction.GetLikeListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	var likeList []video.VideoLiker
	var likeCount int64
	if err := mysql.Db.Model(&video.VideoLiker{}).Where("user_id = ?", req.UserId).Scopes(mysql.PageSelect(int(req.PageNumber), int(req.PageSize))).Find(&likeList).Count(&likeCount).Error; err != nil {
		c.String(consts.StatusInternalServerError, "无法获取点赞列表")
		return
	}

	resp := new(interaction.GetLikeListResponse)
	resp.LikeCount = int32(likeCount)

	for i := range likeList {

		resp.VideoList = append(resp.VideoList, likeList[i].Video)
	}
	resp.BaseResponse = &interaction.BaseResponse{
		StatusCode: http.StatusOK,
		StatusMsg:  "success",
	}
	c.JSON(consts.StatusOK, resp)
}

// CommentVideo .
// @router /comment/pubilsh [POST]
func CommentVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interaction.CommentVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	accesstoken := c.GetHeader("Authorization")

	claims := token.ParseToken(string(accesstoken))
	if claims == nil {
		c.String(consts.StatusUnauthorized, "无效的Token")
		return
	}
	if claims.UserId != req.CommentId {
		c.String(consts.StatusUnauthorized, "请使用你本人的id去评论")
		return
	}
	var myvideo video.Video
	if err := mysql.Db.Model(&video.Video{}).Where("video_id = ?", req.VideoId).First(&myvideo).Error; err != nil {

		c.String(consts.StatusNotFound, "视频不存在")
		return
	}
	userId := claims.UserId
	var myvideocomment interaction.Comment
	myvideocomment.UserId = userId
	myvideocomment.VideoId = req.VideoId
	myvideocomment.Content = req.CommentText
	myvideocomment.CreatedAt = myutils.TsToStr(time.Now().Unix(), "2006-01-02 15:04:05")
	myvideocomment.UpdatedAt = myutils.TsToStr(time.Now().Unix(), "2006-01-02 15:04:05")
	myvideocomment.DeletedAt = ""
	myvideocomment.Id = myutils.GenerateCommentID()
	if err := mysql.Db.Model(&interaction.Comment{}).Create(&myvideocomment).Error; err != nil {
		c.String(consts.StatusInternalServerError, "无法发布评论")
		return
	}

	resp := new(interaction.CommentVideoResponse)
	resp.CommentId = myvideocomment.Id
	resp.BaseResponse = &interaction.BaseResponse{
		StatusCode: http.StatusOK,
		StatusMsg:  "success",
	}

	// 更新 Redis 排行榜
	myredis.Rdb.ZIncrBy(ctx, "video_list", 1, req.VideoId)
	// 更新数据库访问量
	mysql.UpdateVideoVisitCount(req.VideoId)

	c.JSON(consts.StatusOK, resp)
}

// GetCommentList .
// @router /comment/list [GET]
func GetCommentList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interaction.GetCommentListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	var commentList []interaction.Comment
	var commentCount int64
	if err := mysql.Db.Model(&interaction.Comment{}).Where("video_id = ?", req.VideoId).Scopes(mysql.PageSelect(int(req.PageNumber), int(req.PageSize))).Find(&commentList).Count(&commentCount).Error; err != nil {
		c.String(consts.StatusInternalServerError, "无法获取评论列表")
		return
	}
	resp := new(interaction.GetCommentListResponse)
	for i := range commentList {
		resp.CommentList = append(resp.CommentList, &commentList[i])
	}
	resp.CommentCount = int32(commentCount)
	resp.BaseResponse = &interaction.BaseResponse{
		StatusCode: http.StatusOK,
		StatusMsg:  "success",
	}
	c.JSON(consts.StatusOK, resp)
}

// DeleteComment .
// @router /comment/delete [POST]
func DeleteComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interaction.DeleteCommentRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	accesstoken := c.GetHeader("Authorization")

	claims := token.ParseToken(string(accesstoken))
	if claims == nil {
		c.String(consts.StatusUnauthorized, "无效的Token")
		return
	}
	userId := claims.UserId
	var comment interaction.Comment
	if err := mysql.Db.Model(&interaction.Comment{}).Where("id = ?", req.CommentId).First(&comment).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			c.String(consts.StatusNotFound, "评论不存在")
			return
		}
		c.String(consts.StatusInternalServerError, "数据库错误")
		return
	}
	if comment.UserId != userId {
		c.String(consts.StatusForbidden, "你没有权限删除这个评论")
		return
	}
	if err := mysql.Db.Model(&interaction.Comment{}).Where("id = ?", req.CommentId).Delete(&interaction.Comment{}).Error; err != nil {
		c.String(consts.StatusInternalServerError, "无法删除评论")
		return
	}

	resp := new(interaction.DeleteCommentResponse)
	resp.BaseResponse = &interaction.BaseResponse{
		StatusCode: http.StatusOK,
		StatusMsg:  "success",
	}

	c.JSON(consts.StatusOK, resp)
}
