// Code generated by hertz generator.

package video

import (
	"TikTok/mw/token"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{token.JWT()}
}

func _getvideolistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videopopularMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videosearchMw() []app.HandlerFunc {
	// your code...
	return nil
}
