// Code generated by hertz generator.

package video

import (
	"context"

	video "TikTok/biz/model/video"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// PublishVideo .
// @router /video/publish [POST]
func PublishVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PublishVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.PublishVideoResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetVideoList .
// @router /video/list [GET]
func GetVideoList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.GetVideoListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.GetVideoListResponse)

	c.JSON(consts.StatusOK, resp)
}

// VideoSearch .
// @router /video/search [GET]
func VideoSearch(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.VideoSearchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.VideoSearchResponse)

	c.JSON(consts.StatusOK, resp)
}

// VideoPopular .
// @router /video/popular [GET]
func VideoPopular(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.VideoPopularRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.VideoPopularResponse)

	c.JSON(consts.StatusOK, resp)
}
