// Code generated by hertz generator.

package video

import (
	"context"
	"fmt"
	"net/http"
	"time"

	video "TikTok/biz/model/video"
	"TikTok/dal/mysql"
	"TikTok/mw/token"
	myutils "TikTok/utils"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/h2non/filetype"
)

// PublishVideo .
// @router /video/publish [POST]
func PublishVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.PublishVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	videofile, err := c.FormFile("data")
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	videobody, err := videofile.Open()
	if err != nil {
		c.String(consts.StatusInternalServerError, "无法打开上传的视频文件")
		return
	}
	defer videobody.Close()
	buf := make([]byte, 261)
	_, err = videobody.Read(buf)
	if err != nil {
		c.String(consts.StatusInternalServerError, "无法读取上传的视频文件")
		return
	}
	if !filetype.IsVideo(buf) {
		c.String(consts.StatusBadRequest, "上传的文件不是视频格式")
		return
	}
	videotitle := c.PostForm("title")
	if videotitle == "" {
		c.String(consts.StatusBadRequest, "视频标题不能为空")
		return
	}
	videodescription := c.PostForm("description")
	if videodescription == "" {
		c.String(consts.StatusBadRequest, "视频描述不能为空")
		return
	}
	userclaims := token.ParseToken(req.AccessToken)
	if userclaims == nil {
		c.String(consts.StatusUnauthorized, "无效的访问令牌")
		return
	}
	myvideo := video.Video{
		VideoId:      myutils.GenerateVideoID(),
		AuthorId:     userclaims.UserId,
		Title:        videotitle,
		Description:  videodescription,
		CreatedAt:    myutils.TsToStr(time.Now().Unix(), "2006-01-02 15:04:05"),
		UpdatedAt:    myutils.TsToStr(time.Now().Unix(), "2006-01-02 15:04:05"),
		CoverUrl:     "",
		LikeCount:    0,
		CommentCount: 0,
	}

	videourl := fmt.Sprintf("userdata/%s/%s_%s", myvideo.AuthorId, myvideo.VideoId, videofile.Filename)
	myvideo.VideoUrl = videourl
	err = c.SaveUploadedFile(videofile, videourl)
	if err != nil {
		c.String(consts.StatusInternalServerError, "无法保存上传的视频文件")
		return
	}
	if err := mysql.Db.Create(&myvideo).Error; err != nil {
		c.String(consts.StatusInternalServerError, "无法保存视频信息到数据库")
		return
	}
	resp := new(video.PublishVideoResponse)
	resp.VideoId = myvideo.VideoId
	resp.Base = &video.BaseResponse{
		StatusCode: http.StatusOK,
		StatusMsg:  "视频发布成功",
	}
	c.JSON(consts.StatusOK, resp)
}

// GetVideoList .
// @router /video/list [GET]
func GetVideoList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.GetVideoListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	var videos []video.Video
	var videoCount int64
	VideoData := mysql.Db.Model(&video.Video{}).Where("author_id = ?", req.UserId)
	if err := VideoData.Scopes(mysql.PageSelect(int(req.PageNum), int(req.PageSize))).Find(&videos).Count(&videoCount).Error; err != nil {
		c.String(consts.StatusInternalServerError, "无法获取视频列表")
		return
	}

	resp := new(video.GetVideoListResponse)
	for i := range videos {

		resp.Videos = append(resp.Videos, &videos[i])
	}
	resp.Base = &video.BaseResponse{
		StatusCode: http.StatusOK,
		StatusMsg:  "获取视频列表成功",
	}
	c.JSON(consts.StatusOK, resp)
}

// VideoSearch .
// @router /video/search [GET]
func VideoSearch(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.VideoSearchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	var videolist []video.Video
	if err := mysql.Db.Model(&video.Video{}).Where("title LIKE ? OR description LIKE ?", req.Keyword, req.Keyword).Scopes(mysql.PageSelect(int(req.PageNum), int(req.PageSize))).Find(&videolist).Error; err != nil {
		c.String(consts.StatusInternalServerError, "无法搜索视频")
		return
	}
	resp := new(video.VideoSearchResponse)
	for i := range videolist {
		resp.Videos = append(resp.Videos, &videolist[i])
	}
	resp.Base = &video.BaseResponse{
		StatusCode: http.StatusOK,
		StatusMsg:  "搜索视频成功",
	}
	c.JSON(consts.StatusOK, resp)
}

// VideoPopular .
// @router /video/popular [GET]
func VideoPopular(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.VideoPopularRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.VideoPopularResponse)

	c.JSON(consts.StatusOK, resp)
}
