// Code generated by hertz generator.

package communication

import (
	"context"

	communication "TikTok/biz/model/communication"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Subscribe .
// @router /relation/action [POST]
func Subscribe(ctx context.Context, c *app.RequestContext) {
	var err error
	var req communication.SubscribeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(communication.SubscribeResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetSubscriberList .
// @router /following/list [GET]
func GetSubscriberList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req communication.GetSubscriberListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(communication.GetSubscriberListResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetFansList .
// @router /follower/list [GET]
func GetFansList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req communication.GetFansListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(communication.GetFansListResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetFriendList .
// @router /friend/list [GET]
func GetFriendList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req communication.GetFriendListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(communication.GetFriendListResponse)

	c.JSON(consts.StatusOK, resp)
}
