// Code generated by hertz generator.

package userhandler

import (
	"context"

	userhandler "TikTok/biz/model/userhandler"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Register .
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userhandler.RegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(userhandler.RegisterResponse)

	c.JSON(consts.StatusOK, resp)
}

// Login .
// @router /user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userhandler.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(userhandler.LoginResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetUserInfo .
// @router /user/info [GET]
func GetUserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userhandler.UserInfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(userhandler.UserInfoResponse)

	c.JSON(consts.StatusOK, resp)
}

// PostUserPhoto .
// @router /user/avatar/upload [POST]
func PostUserPhoto(ctx context.Context, c *app.RequestContext) {
	var err error
	var req userhandler.UserphotoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(userhandler.UserphotoResponse)

	c.JSON(consts.StatusOK, resp)
}
