// Code generated by hertz generator.

package user

import (
	"context"
	"fmt"
	"image"
	_ "image/gif"
	_ "image/jpeg"
	_ "image/png"
	"log"
	"net/http"
	"os"
	"time"

	user "TikTok/biz/model/user"
	"TikTok/dal/mysql"
	myutils "TikTok/utils"

	"TikTok/mw/token"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Register .
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	var u user.User
	u = user.User{
		Id:        myutils.GenerateUserID(),
		Username:  req.Username,
		Password:  myutils.HashPassword(req.Password),
		CreatedAt: myutils.TsToStr(time.Now().Unix(), "2006-01-02 15:04:05"),
		UpdatedAt: myutils.TsToStr(time.Now().Unix(), "2006-01-02 15:04:05"),
		DeletedAt: "",
	}
	if err = mysql.Db.Create(&u).Error; err != nil {
		c.JSON(http.StatusInternalServerError, user.RegisterResponse{
			Base: &user.BaseResponse{
				StatusCode: 1,
				StatusMsg:  "注册失败",
			},
		})
		return
	}
	resp := new(user.RegisterResponse)
	resp.Base = &user.BaseResponse{
		StatusCode: 0,
		StatusMsg:  "注册成功",
	}
	resp.UserId = u.Id
	userdatapath := fmt.Sprintf("userdata/%s/", u.Id)
	if err := os.MkdirAll(userdatapath, 0755); err != nil {
		log.Printf("创建用户数据目录失败: %v", err)
	}
	c.JSON(consts.StatusOK, resp)
}

// Login .
// @router /user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 查询用户是否存在
	var u user.User
	log.Printf("尝试登录 - 用户名: %s", req.Username)
	if err = mysql.Db.Where("username = ?", req.Username).First(&u).Error; err != nil {

		c.JSON(http.StatusInternalServerError, user.LoginResponse{
			Base: &user.BaseResponse{
				StatusCode: 1,
				StatusMsg:  "用户名或密码错误",
			},
		})
		return
	}

	// 验证密码

	if !myutils.CompareHashAndPassword(req.Password, u.Password) {
		c.JSON(http.StatusInternalServerError, user.LoginResponse{
			Base: &user.BaseResponse{
				StatusCode: 1,
				StatusMsg:  "用户名或密码错误",
			},
		})
		return
	}

	// 生成 token
	accesstoken, refreshtoken, err := token.GenerateToken(u.Id, u.Username)
	if err != nil {
		c.JSON(http.StatusInternalServerError, user.LoginResponse{
			Base: &user.BaseResponse{
				StatusCode: 1,
				StatusMsg:  "生成 token 时发生错误",
			},
		})
		return
	}

	resp := new(user.LoginResponse)
	resp.UserId = u.Id
	resp.AccessToken = accesstoken
	resp.Base = &user.BaseResponse{
		StatusCode: 0,
		StatusMsg:  "登录成功",
	}
	c.SetCookie("refresh_token", refreshtoken, 3600*24, "/", "", protocol.CookieSameSite(http.SameSiteLaxMode), true, true)
	c.JSON(consts.StatusOK, resp)
}

// GetUserInfo .
// @router /user/info [GET]
func GetUserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserInfoRequest
	err = c.BindAndValidate(&req)
	fmt.Println(req.UserId)
	if req.UserId == "" {
		c.String(consts.StatusBadRequest, "用户ID不能为空")
		return
	}
	log.Printf("尝试获取用户信息 - 用户ID: %s", req.UserId)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	var u user.User
	if err := mysql.Db.Model(&user.User{}).Where("Id = ?", req.UserId).First(&u).Error; err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := new(user.UserInfoResponse)
	resp.User = &user.Userinfo{
		Id:        u.Id,
		Username:  u.Username,
		PhotoUrl:  u.PhotoUrl,
		CreatedAt: u.CreatedAt,
		UpdatedAt: u.UpdatedAt,
		DeletedAt: u.DeletedAt,
	}
	resp.Base = &user.BaseResponse{
		StatusCode: http.StatusOK,
		StatusMsg:  "获取用户信息成功",
	}

	c.JSON(consts.StatusOK, resp)
}

// PostUserPhoto .
// @router /user/avatar/upload [POST]
func PostUserPhoto(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserphotoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	file, err := c.FormFile("data")
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	dstfile := fmt.Sprintf("userdata/%s/%s_%s", req.UserId, req.UserId, file.Filename)

	// 保存文件
	photoMaxize := int64(10 << 20) // 10MB
	if file.Size > photoMaxize {
		c.String(consts.StatusBadRequest, "文件过大，最大支持10MB")
		return
	}
	fileContent, err := file.Open()
	if err != nil {
		c.String(consts.StatusInternalServerError, "无法打开上传的文件")
		return
	}
	defer fileContent.Close()
	config, format, err := image.DecodeConfig(fileContent)
	if err != nil {
		c.String(consts.StatusBadRequest, "无法识别的图片格式")
		return
	}
	if format != "jpeg" && format != "png" && format != "gif" {
		c.String(consts.StatusBadRequest, "不支持的图片格式，仅支持JPEG、PNG和GIF")
		return
	}
	if config.Width > 5000 || config.Height > 5000 {
		c.String(consts.StatusBadRequest, "图片尺寸过大，最大支持5000x5000像素")
		return
	}
	if err = c.SaveUploadedFile(file, dstfile); err != nil {
		c.String(consts.StatusInternalServerError, "文件保存失败")
		return
	}
	photoUrl := fmt.Sprintf("/%s", dstfile)
	req.PhotoUrl = photoUrl
	// 更新用户头像URL
	var u user.User
	if err = mysql.Db.Model(&user.User{}).Where("id = ?", req.UserId).First(&u).Error; err != nil {
		c.String(consts.StatusInternalServerError, "用户不存在")
		return
	}
	if u.PhotoUrl != "" {
		oldPhotoPath := u.PhotoUrl[1:] // 去掉前面的斜杠
		if err = os.Remove(oldPhotoPath); err != nil {
			log.Printf("删除旧头像失败: %v", err)
			c.String(consts.StatusInternalServerError, "无法删除旧头像")
			return
		}
		c.String(consts.StatusOK, "上传新头像成功，旧头像已被删除")
	}
	if err = mysql.Db.Model(&user.User{}).Where("id = ?", req.UserId).Update("photo_url", req.PhotoUrl).Error; err != nil {
		c.String(consts.StatusInternalServerError, "更新用户头像URL失败")
		return
	}

	resp := new(user.UserphotoResponse)
	resp.StatusCode = http.StatusOK
	resp.StatusMsg = "上传头像成功"

	c.JSON(consts.StatusOK, resp)
}
