// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	api "TikTok/biz/router/api"
	communication "TikTok/biz/router/communication"
	interaction "TikTok/biz/router/interaction"
	user "TikTok/biz/router/user"
	video "TikTok/biz/router/video"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	api.Register(r)

	communication.Register(r)

	interaction.Register(r)

	video.Register(r)

	user.Register(r)
}
